version: '3'
services:
  back:
    build: ./back/.
    ports:
    - "6060:6060"
    volumes:
    - ./back:/go/src/back
  front:
    build: ./front/.
    ports:
    - "8080:8080"
    volumes:
    - ./front:/usr/src/app
