FROM golang:1.10

EXPOSE 8080

RUN go get github.com/smartystreets/goconvey
RUN ["go", "get", "github.com/gorilla/mux"]
RUN ["go", "get", "github.com/joho/godotenv"]
RUN ["go", "get", "github.com/go-sql-driver/mysql"]

WORKDIR /go/src/test_simple_app_vue_go/back
COPY . .

EXPOSE 8080
CMD goconvey -host 0.0.0.0
